### ISSUE TITLE
Docker Hub: keep in sync with this repository

### ISSUE THREAD

**Issue by diabonas** [tpm2-software/tpm2-software-container#4]
The [Docker Hub image](https://hub.docker.com/r/tpm2software/tpm2-tss) is built based on the [tss-build-robot fork](https://www.github.com/tss-build-robot/tpm2-software-container) of this repository, which is currently not up to date. As a result, the tpm2-tools CI [still fails](https://travis-ci.org/tpm2-software/tpm2-tools/jobs/512529250#L2653) despite #2 being merged here. Either
- setup Docker Hub to pull from this repository directly, or
- use something like the [GitHub Pull app](https://github.com/apps/pull) for [tss-build-robot/tpm2-software-container](https://www.github.com/tss-build-robot/tpm2-software-container) to keep the fork in sync with upstream.

**Comment by tstruk** [comment]
Changed dockerhub build settings to use tpm2-software/tpm2-software-container directly
