### ISSUE TITLE
Outdated Fedora dependencies

### ISSUE THREAD

**Issue by MikeSpreitzer** [tpm2-software/tpm2-software-container#65]
I am trying to build on Fedora 34.  The dependencies listed in https://github.com/tpm2-software/tpm2-tools/blob/master/doc/INSTALL.md#fedora , namely

```
$ sudo dnf -y update && sudo dnf -y install automake libtool \
autoconf autoconf-archive libstdc++-devel gcc pkg-config \
uriparser-devel libgcrypt-devel dbus-devel glib2-devel \
compat-openssl10-devel libcurl-devel PyYAML
```

have a few problems.

There are no packages named compat-openssl10-devel and PyYAML.  Thus far I am installing openssl-devel and python3-pyyaml instead, not sure whether I will succeed.

That list does not include pandoc.

I found that tpm2-tss now requires `json-c` as well.  And there is a `json-c` package, but installing it still does not satisfy tpm2-tss.

Even after the adjustments above, `dnf -y builddep tpm2-tss` says

```
Installing:
 doxygen                                                         x86_64                            1:1.9.1-10.fc34                                     updates                            4.7 M
 gcc-c++                                                         x86_64                            11.1.1-3.fc34                                       updates                             12 M
 json-c-devel                                                    x86_64                            0.14-8.fc34                                         fedora                              45 k
Installing dependencies:
...
```
(and there is a _long_ list of dependencies included).

**Comment by williamcroberts** [comment]
We have fedora-34 now in the builds.
